steps:
# 1. Initialize Terraform
- id: 'terraform init'
  # Use a publicly available Terraform Docker image (builder)
  name: 'hashicorp/terraform:latest'
  entrypoint: 'terraform'
  # Command arguments: terraform init
  args: ['init', '.'] 

# 2. Generate a Plan (preview changes)
- id: 'terraform plan'
  name: 'hashicorp/terraform:latest'
  entrypoint: 'terraform'
                                                                     #  Command arguments: terraform plan -out=tfplan -var="project_id=${PROJECT_ID}"
  args: ['plan', '-out=tfplan', '-var', 'project_id=${PROJECT_ID}']

# 3. Apply the Plan (deploy changes)
# This step is often conditional to prevent accidental deployments
# For a basic example, we include it here:
- id: 'terraform apply'
  name: 'hashicorp/terraform:latest'
  # Command arguments: terraform apply tfplan
  entrypoint: 'terraform'
  args: ['apply', 'tfplan']

  # Set a timeout for the apply step to prevent indefinite runs
  timeout: '1200s' 

# Optional: Define default substitution variables for use in the steps
substitutions:
  # PROJECT_ID is often automatically provided by Cloud Build but can be defined here
  _PROJECT_ID: 'my-gcp-project-id'